// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMGO2Cq80W0ytWeLkHGmgvbzd-hlXAq_Y',
    appId: '1:105087641354:web:90f02512a74c84ad68fcf3',
    messagingSenderId: '105087641354',
    projectId: 'quiz-app-flutter-3cfdb',
    authDomain: 'quiz-app-flutter-3cfdb.firebaseapp.com',
    storageBucket: 'quiz-app-flutter-3cfdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_TRGSmaycOCDQ9ADIXwgFfIZx1zyhhCg',
    appId: '1:105087641354:android:e37d0ba8dcf154e168fcf3',
    messagingSenderId: '105087641354',
    projectId: 'quiz-app-flutter-3cfdb',
    storageBucket: 'quiz-app-flutter-3cfdb.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMGO2Cq80W0ytWeLkHGmgvbzd-hlXAq_Y',
    appId: '1:105087641354:web:26f48df9f29ebb4168fcf3',
    messagingSenderId: '105087641354',
    projectId: 'quiz-app-flutter-3cfdb',
    authDomain: 'quiz-app-flutter-3cfdb.firebaseapp.com',
    storageBucket: 'quiz-app-flutter-3cfdb.appspot.com',
  );
}